spring.application.name=EmployeeManagement


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sivasai
spring.datasource.password=Siva@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
